version: '3'

services:
  goubiq_redis:
    container_name: goubiq_redis
    image: redis
    ports:
      - "6379:6379"

  goubiq_python:
    container_name: goubiq_python
    build: ./python/
    depends_on:
      - goubiq_redis
    entrypoint:
      - python
      - poll.py
    volumes:
      - ./python/:/mnt/src
    ports:
      - '8081:8081'


  goubiq_node:
      image: peter/node
      container_name: goubiq_node
      ports:
       - '8080:8080'
       - '80:80'
      build: ./node/
      entrypoint: nodemon --watch ./ -e js,html  app.js
      volumes:
       - ./node/:/mnt/src

